### ISSUE TITLE
double_float syntactic Boost backend reqs

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#12]
This iss ue tracks implementing `double_float`'s syntactic Boost backend requirements such as the `eval_whatever` functions, the tuple of types, etc.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

I request you to please provide me with an outline of Boost backend requirements. It will help me to plan the implementation and the course of action on the issue.

Thank you in advance.
Fahad

**Comment by ckormanyos** [comment]
Hi @sinandredemption there is a great deal of quality support available in the code and docs to assist with writing a custom Multiprecision backend.

At the moment, let's restrict ourselves to the `double_float`template class. As we progress, the same words and guidance will apply to the future `quad_float` class.

One starting point is to look at the backend requirements and manually write the necessary functions. I have done this on several occasions and always had success with manual writing. An example of this can be found in the legacy [e_float project](https://github.com/ckormanyos/e_float-2021/blob/main/libs/math/include/boost/math/bindings/e_float.hpp).

A few years back @jzmaddock wrote a so-called _skeleton_ class specifically designed for those seeking to write their own Multiprecision backend via template support of a known working example. The documentation on using the skeleton backend can be found [here](https://www.boost.org/doc/libs/1_76_0/libs/multiprecision/doc/html/boost_multiprecision/tut/new_backend.html). This page also guides as regarding which tests we should add.

When you write these backend requirements, you will also pleasantly find that not all forms of binary arithmetic are actually required, as would be the case for a standalone class. So while we have conceptually spoken of making a standalone class in and of iteself in its own entirety, we could modify that opinion at this time. You could, in fact, progress rather quickly toward wrapping `double_float` as a Multiprecision backend. I think we have most of the necessary operators available at this time.

We should, and we will, however, need certain considerations for some elementary `<cmath>`-style functions such as, most importantly, `frexp`, `ldexp`, `floor`, `ceil`. It really makes sense to write these manually for the backend. Other functions such as trigonometric functions and power functions can be synthesized. But it also makes sense to make some fast approximations for trigonometric functions such as sine, cosine and power functions exponentiation, logarithm. For the `double_float` case, such approximations need to be in multiple digit ranges since instantiation with `float`, `double`, etc. lead to vastly different digit ranges.

At first, however, you might consider giving the skeleton mentioned above a try. Also look at the previous work in the qd branch which wrapped the original LIB for Multiprecision, but never fully, let's say, got off the ground.

**Comment by ckormanyos** [comment]
Hi @sinandredemption for the sake of completeness (and I have used this guide many times) for writing a Boost.Multiprecision backend, you can also study the manually written backend requirements [here](https://www.boost.org/doc/libs/1_76_0/libs/multiprecision/doc/html/boost_multiprecision/ref/backendconc.html).

As you can see, the absolute mandatory requirements initially setup by @jzmaddock are quite skinny, requiring just a few operators and functions. The operators take the form of functions with names such as `eval_add`, etc. This can be a good way to go if you already have a relatively complete class and you just need to, let's say, put the multiprecision syntactic sugar on top.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Thank you for your detailed suggestions. I will go through the links you provided and research further on this. I am getting excited seeing the advancement of our project.

Cheers,
Fahad

**Comment by ckormanyos** [comment]
> ... go through the links you provided and research further on this.

Right on!

> I am getting excited seeing the advancement of our project.

Indeed. It is cool to see this coming together and taking shape.

Your `double_float` class is getting in shape for wrap-to-Boost. In fact, you  have already done the hard parts, which are the algos for add/sub/mul/div/sqrt. We should look at `frexp`, `ldexp`, `floor` and `ceil`. Then we can effectively wrap `double_float` for Boost.

At any later time, I can swing in with some optimizations for trigonometrics and exponentials.

We can work on John's suggested backend test suites together.

This entire exercise will put you in a truly poised position to start tackling `quad_float`.

Take a look and see how it goes...

**Comment by ckormanyos** [comment]
This is moving forward in the `gsoc2021_double_float_backend_reqs` branch.

There are a few known problems before completing the draft of `double_float` as a formal Multiprecision backend.

1. Function content needed for `eval_sqrt()`
2. Function content needed for `eval_ldexp()`
3. Specific multiplication tests broken for GCC's 10-byte `long double`

Other than those problems, the work in the branch is getting really close to being capable of being pushed to develop.

@sinandredemption and @cosurgi if time allows, it would be good if you have any time to review this work. Or if anyone can contribute to those major open points listed, that ywould be great, as I'm kind of stuck on these.

**Comment by ckormanyos** [comment]
>  content needed for `eval_sqrt()`

OK, got a rudimentary implementation of square root running and testing.

**Comment by ckormanyos** [comment]
> content needed for `eval_ldexp()`

OK, got a rudimentary implementation of `eval_ldexp()` running and testing.

**Comment by ckormanyos** [comment]
@sinandredemption the Boost backend wrap is also very close to supporting a cascade in the form of:

```
boost::multiprecision::number<boost::multiprecision::backends::cpp_double_float<boost::multiprecision::backends::cpp_double_float<double>>, boost::multiprecision::et_off>
```

I have taken care of several issues related to this, such as numeric limits and a few other specializations along the way. A few functions such as namespace-specific versions of `ldexp` (not in its `eval_`-form), and maybe a few more are needed. These should be simple enough. You might like to take a look, as this is getting close...

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

> the Boost backend wrap is also very close to supporting a cascade

That sounds perfect! May I run the arithmetic tests for the cascade right away?

**Comment by ckormanyos** [comment]
> May I run the arithmetic tests for the cascade right away?

Unfortunately, we still need a bit of syntax magic still I haven't figured out if its best in Boost.Math or Boost.Multiprecision permanently. For the moment, you will find that cascading down requires functions like `ldexp(cpp_double_float<T>, int)` and these we need to implement in the namespace `boost::multiprecision::backends` for out naked double float class.

If you uncomment my arithmetic tests [this line](https://github.com/BoostGSoC21/multiprecision/blob/d3a624831654e74f49625046543d3de1fa5c1fa6/test/test_cpp_double_float_arithmetic.cpp#L361) and also look at the cascading of the control values around [here](https://github.com/BoostGSoC21/multiprecision/blob/d3a624831654e74f49625046543d3de1fa5c1fa6/test/test_cpp_double_float_arithmetic.cpp#L180) and a few other places, you can see how close we get to the cascading in, for example, MSVC.

**Comment by ckormanyos** [comment]
The standard Multiprecision tests are close to passing in the `gsoc2021_double_float_backend_reqs` branch.

Running for instantiation of `number<cpp_double_float<double>>` gives 14 errors, mostly problems with `inf`, shown below. As such these should be relatively easy to handle. Will handle these shortly.

```
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and unsigned char
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and signed char
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and signed char
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and char
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and char
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and short
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and short
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and unsigned short
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and int
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and int
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and unsigned int
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and long
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and long
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and unsigned long
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and __int64
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and __int64
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and unsigned __int64
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and float
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and float
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and double
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and double
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and long double
Testing mixed arithmetic with type: class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0> and long double
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1343 Failed predicate: (boost::math::isinf)(Real(20) / 0u)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1418 Failed predicate: (boost::math::isinf)(v + r)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1419 Failed predicate: (boost::math::isinf)(r + v)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1420 Failed predicate: (boost::math::isinf)(r - v)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1421 Failed predicate: (boost::math::isinf)(v - r)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1422 Failed check for less than:
Value of LHS was: nan
Value of RHS was: 0

In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1425 Failed predicate: (boost::math::isinf)(r / v)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1426 Failed check for equality:
Value of LHS was: nan
Value of RHS was: 0

In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1428 Failed predicate: (boost::math::isinf)(t += r)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1430 Failed predicate: (boost::math::isinf)(t += v)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1432 Failed predicate: (boost::math::isinf)(t -= v)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1434 Failed predicate: (boost::math::isinf)(t -= r)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1442 Failed predicate: (boost::math::isinf)(t /= v)
In function: void __cdecl test_float_ops<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,0>>(const struct std::integral_constant<int,1> &)
C:\boost\modular_boost\boost\libs\multiprecision\test\test_arithmetic.hpp:1444 Failed predicate: (t /= r) == 0
14 errors detected.```

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

I have tried to have fix some simple problems with handling of `inf` and `nan` in [this commit](https://github.com/BoostGSoC21/multiprecision/commit/2a91e292dab33db81bcbc8bbe97f79199fc100ac). I have used the standard Boost test file `test_arithmetic.hpp` as the reference for test cases.

However, now I am get a [list of errors](https://github.com/BoostGSoC21/multiprecision/files/6893916/errors.txt) related to lexical casts that I unfortunately couldn't comprehend completely. In particular, could you tell me the exact intention behind the lexical cast tests? And why they seem to be throwing memory exceptions?

**Comment by sinandredemption** [comment]
@ckormanyos Nevermind, the failed test cases were due to a silly bug caused by a single missing character that I must have overlooked while copy-pasting.

**Comment by ckormanyos** [comment]
> due to a silly bug caused by a single missing character 

Yes. i saw that missing logical not `!` symbol. There are a few more failures due to finite/infinite not being zero and the like.

I am about to check in some stuff with a bunch of those issues fixed.

**Comment by ckormanyos** [comment]
> am about to check in some stuff with a bunch of those issues fixed.

This might take an iteration or two from my side, but I'm trying to get:
- Our arithmetic test
- Boost's arithmetic tests (also for float128)
- Our constructor tests

All running on CI.

Assuming success, I#d like to wait and see if I can get to go green. Then i'd like to merge to develop of the fork.

**Comment by ckormanyos** [comment]
Hi @sinandredemption and @cosurgi so it is looking good in CI (even though GHA is a bit shaky today for some reason). The Boost-like arithmetic tests and our own numerical tests are going green in CI. As mentioned in another thread, this means that `double_float` is fully viable as a Boost backend candidate --- in early stages --- but having loads of potential. Yeah!

Great work guys!

As soon as GHA comes to its senses, I'll merge this stuff to develop of the fork.

I will try on my own to handle:
- Refinements of `std::numeric_limits<number<cpp_double_float<T>>>`
- Figure out what's wrong with 10-byte `ling double`on GCC.

@sinandredemption full speed ahead on any plans you have to refine either the backend reqs branch (of `double_float`) or feel free to unabatedly press on with drafting new stuff for `quad_float`.

**Comment by ckormanyos** [comment]
Finished in the first draft with the backend requirements of #34
