### ISSUE TITLE
double_float input streaming

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#13]
Implement near-compliant input streaming support

**Comment by ckormanyos** [comment]
Implement near-standards-conformant input streaming from `stream`-to-`double_float`.

A legacy project supplied as an example in a branch might help, see the `rd_string` method [here](https://github.com/BoostGSoC21/multiprecision/blob/5bddfa9f56dd000de7077b11532f0305f4880911/example/q_float/q_float/q_float.cpp#L672).

**Comment by ckormanyos** [comment]
Question: Should stream input from string support C++14 digit separators?

**Comment by cosurgi** [comment]
I wonder - is there something similar to these [`eval_*` routines](https://www.boost.org/doc/libs/1_76_0/libs/multiprecision/doc/html/boost_multiprecision/ref/backendconc.html) mentioned in #12 which would deal with string streaming and maybe C++14 digit separators and other stuff?

**Comment by sinandredemption** [comment]
@ckormanyos Since Boost's own routines are seemingly doing fine handling I/O, feel free to close this issue in case there isn't anything to discuss about `cpp_double_float`'s specialization of input streaming.

**Comment by ckormanyos** [comment]
> feel free to close this issue

Done. If further issue arise in more complete testing in the future, these will be handled in separate issue(s).
