### ISSUE TITLE
specfun CI tests for cpp_double_fp_backend

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#131]
The purpose of this issue is to get the specfun GHA CI tests running for the `cpp_double_fp_backend<>` template type.

Instantiate at first for `double` and see how that goes. If more needed, such as `__float128`, we will decide as we go.

Cc: @sinandredemption and @cosurgi

**Comment by ckormanyos** [comment]
I will take the first try at this.

**Comment by ckormanyos** [comment]
We have now `specfun` running (but failing as expected) on develop in CI for `cpp_double_fp< 8-byte-double >`.
At the moment 11 files fail.
See detailed comments in #138

Cc: @sinandredemption and @cosurgi

**Comment by ckormanyos** [comment]
Correction: See #138

**Comment by ckormanyos** [comment]
We keep moving forward, now with only 5 files failing `specfun` in CI for `cpp_double_fp< 8 -byte-double >`.

See also #142

Work continues on edge cases which should eventually get all of `specfun` passinf for this data type.

Cc: @sinandredemption

**Comment by ckormanyos** [comment]
Hi Fahad (@sinandredemption) in order to provide very clear and easy-to-understand instances of failing test cases, I have prepared the first of two in a series of failing test case studies.

These can be found in #143 and #144

Cc: @cosurgi

**Comment by ckormanyos** [comment]
We are now down to two and only two meaningful files with failing test cases in `specfun`.
See the comments in #146

Cc: @sinandredemption and @cosurgi

**Comment by ckormanyos** [comment]
>  ... down to two and only two meaningful files with failing test cases in `specfun`.

In particular, see the [build log](https://github.com/BoostGSoC21/multiprecision/actions/runs/4037252447/jobs/6940421861) for #146.

**Comment by ckormanyos** [comment]
See also comments and build logs from #147

**Comment by ckormanyos** [comment]
I just posted in the wrong thread for these specfun tests.

See #136 

Cc: @sinandredemption

**Comment by ckormanyos** [comment]
See also #150

**Comment by ckormanyos** [comment]
Still getting closer to passing all of _specfun_. See detailed comments from #154, repeated here.

Remaining _specfun_ issues include:

- gamma_inv (several issues ALL around extremely small/subnormal values),
- one single exception thrown in `elliptic_3`,
- several issues (still) in `cyl_bessel_k`.

Cc: @sinandredemption and @cosurgi

**Comment by ckormanyos** [comment]
> one single exception thrown in `elliptic_3`

This has been correected in #155. The read of overly large strings (that will be infinite) did not properly regard the result sign of ${\pm}{\infty}$, and they were all positive. Now the sign is correctly retained.

Also the square root of infinity was improperly given in the `eval_sqrt` function as NaN, but it should also be infinity.

**Comment by ckormanyos** [comment]
OK with #157 `cyl_bessel_k` is finished.

The only _specfun_ with remaining test failures is `igamma_inv`, which will be handled specifically in a separate issue.

**Comment by cosurgi** [comment]
This is great work. Thank you very much. And happy New Year! :)

**Comment by ckormanyos** [comment]
> This is great work. Thank you very much. And happy New Year!

Thank you @cosurgi we made a really good start together with @sinandredemption in theoriginal GSoC. It hink we are getting close now to the double-fp-backend.

**Comment by ckormanyos** [comment]
OK. We are down to the final problem on _specfun_.

- In `test_igamma_inv.cpp`, we find the only remaining _specfun_ test failures.
- Furthermore, these are localized to the `gamma_inv_small_data` table.
- The error phenomenon is: _Root finding evaluation exceeded 200 iterations, giving up now_.
- The root-finding does not converge. But the problem might be more closely related to functions like `ldexp`.

I'll try and localize/fix this phenomenon locally.

Cc: @cosurgi and @sinandredemption
