### ISSUE TITLE
double_float add more compiler(s) and OS-es to CI

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#15]
It would be nice to add some more compiler/OS runs to CI including MSVC latest, GCC and clang on MacOS, and maybe MinGW x86_64 host.

**Comment by ckormanyos** [comment]
CI is looking green. I think it is time for me to get a few more cimpilers running on the CI system.

Will report soon...

**Comment by ckormanyos** [comment]
GCC/clang running now on Mac OS in CI

**Comment by cosurgi** [comment]
This is very useful, thank you! :)

**Comment by ckormanyos** [comment]
Just added some address sanitize runs on GCC/clang. CI is cycling...

**Comment by ckormanyos** [comment]
Just added 4 arithmetic `float128` GCC runs to CI. Thanks Janek and Fahad for preparing this.

@cosurgi @sinandredemption

**Comment by ckormanyos** [comment]
Transfer this work to progress in the jam file

**Comment by ckormanyos** [comment]
As a next step, I'll be adding GCC on MacOS and try for MSVC 14.2 runs in CI.

**Comment by ckormanyos** [comment]
Hi @sinandredemption and @cosurgi CI for `cpp_double_float<T>` is now rather well represented within the JAM-file using standard Boost-style.

Open points on testing `cpp_double_float<T>`:

- I still need to clarify a few details with @jzmaddock regarding the best test style how to mix compilers supporting `cpp_double_float<boost::multiprecision::float128>`.
- We still have some problems with round-tripping (see also #20).
- We (or I) still need to look into inter-conversion to/from other multiprecision types, as we have not yet addressed this.
- I still need to handle construction explicit/implicit from scoped/unscoped enumeration.
- Some operator resolutions in `cpp_double_float<T>` seem not yet perfectly correct, as specfun tests are not passing, I'll look into it. Maybe need help at some point from @jzmaddock on this.

But so far, all in all, CI is working and providing some very good results on `cpp_double_float<T>`. So maybe where it makes sense, use the CI from develop of the fork, as this is where I will be focussing future CI efforts as we progress with double/quad-float.

A parallel issue handling CI for the brand new and in progress `cpp_quad_float<T>` is being handled in #52
