### ISSUE TITLE
simple cascade construction fails arithmetic tests

### ISSUE THREAD

**Issue by sinandredemption** [BoostGSoC21/multiprecision#32]
Hello @ckormanyos @cosurgi 

I have been stuck on this so I am posting this as issue, and requesting your thoughts.

Although a simple cascade construction passes most of the arithmetic tests (~95% of the test cases), there are still a considerable number of test cases where it fails. I have a strong suspicion that the reason is not implementation bugs, but algorithmic limitations.

Let me illustrate the patterns I found using an example test case that fails:
```
a     : 0x1.53927b9f51e64p+502 + -0x1.f52e9639f7a13p+448 + -0x1.b506c7f6a22ccp+394 + -0x1.851ac4d572480p+339
b     : 0x1.3ac4c88ef35a7p+483 +  0x1.450357de576f7p+429 + -0x1.92ca92ea25f78p+374 + -0x1.524a82f2514e8p+320
a + b : 0x1.5392a2f7eaf81p+502 + 0x1.a5a51266735a9p+448 + 0x1.06749edcb4a4ap+394 + -0x1.5a6b778f61532p+340
actual: 0x1.5392a2f7eaf81p+502 + 0x1.a5a51266735aap+448 + 0x1.06749edcb4a4ap+394 + -0x1.5a6b778f61532p+340
```
The only difference is the last hex digit of the second part (0x1.a5a51266735a**9**p+448 vs 0x1.a5a51266735a**a**p+448). This pattern is consistent among failed test cases.

It seems though while calculating upper half of the sum there is some bounded error that causes inexact sum in the cascade case on this line from exact_sum():
> `   out.second   = (a - (out.first - v)) + (b - v);`

It seems to me that we have two options now:
1) Find algorithms to get around this problem
2) Overload the arithmetic operators from code in accordance with cpp_quad_float

For option 1, could a carrier bit [as proposed by @cosurgi](https://github.com/BoostGSoC21/multiprecision/issues/26#issuecomment-882531290) help?

Option 2, although very straightforward, would limit our "cascade depth" and hence we might not be able to extend beyond 206 bits of precision using native float types. The routines also would be much longer and more complicated than a simple cpp_double_float

OTOH, if we are going for option 2, then it remains to establish what we are gaining by using a cascade construction. We could just as easily define a separate cpp_quad_float, and using boost-backend style templates, we could implement math functions without rewriting code.

**Comment by sinandredemption** [comment]
Hello @cosurgi @ckormanyos 

All the above mentioned issues can be easily reproduced [in this commit](https://github.com/BoostGSoC21/multiprecision/commit/ccc5f4b6ad253e7f0d7390934732f26f3535a051). For example, [here ](https://github.com/BoostGSoC21/multiprecision/runs/3179502525) are some the failed test cases.

**Comment by ckormanyos** [comment]
> the above mentioned issues can be easily reproduced

Hi @sinandredemption thanks for these keen observations.

Understood. I also observed similar behavior in separate infestigations.

There are a few choices, as you mentioned above. In general, I do not select cascading templates as a first line of choice. My general, subjective experience has been that this obscures the relationship between the visible code and what is actually runing. Furhtermore it also creates problems (or tends to create more problems) when compiling.

Along those lines, I would prefer separate entities for `double_float` and `quad_float`.

On the other hand, instantiation of the cascaded `double_float` is, for the most part, working. So consider this from a purely technical standpoint. It would, in fact, be really technically enriching to see if we can isolate and properly handle the, let's say, selective cases of the missing bit. Perhaps with the implicit bits that Janek has begun to investigate in #26.

If we decide on the former, to create separate Boost-ified entities for `double_float` and `quad_float`, then the newest work in my `gsoc2021_double_float_backend_reqs` branch, described in greater detail in #12 can provide clear guidance on implementing the Boost backend requirements.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Thank you for your thoughts. It seems to me that going ahead with `quad_float` class is the way forward, given the limited time available. And let @cosurgi also continue to investigate the workarounds in #26.

Before marching ahead with `quad_float`, we surely do we have some work pending in the `double_float` class that I could help with (e.g. #33 , #24 etc).

What would you suggest?

**Comment by ckormanyos** [comment]
> What would you suggest?

A few thoughts based on yours...

> going ahead with quad_float class is the way forward.

I agree.

> some work pending in the `double_float` class.

Yes. We need to find a way to regain a common ground on the develop branch.

We need to move forward on `double_ float` --- toward a truly Boost-ified backend. In my backend-reqs branch, pretty much everything works for arithmetic tests except NaNs and infinities. Unfortunately, however, I found some way to break the proper functionality of 10-bit `long double` on x86_64 GCC.

So if everyone like @sinandredemption and @cosurgi agrees, i would suggest to:
- Merge my work from the Boost-ified `double_float` to develop.
- Eventually (with lesser priority) figure out how i broke and how to fix 10-byte `long double`.
- Migrate to the real kind of Boost-style testing as a formally correct backend, see also #25.

In combination with these points (and those you mention), we will have a rather good, fully Boost-ified implementation of `double_float`. Using this as a guide, you will find it much more simple to make a quick run at `quad_double`.

OK?

**Comment by sinandredemption** [comment]
@ckormanyos Seems like the way to go.

> Eventually (with lesser priority) figure out how i broke and how to fix 10-byte long double.

Is their a way I can reproduce the issue on my system (for debugging)?

> Migrate to the real kind of Boost-style testing as a formally correct backend, see also CI testing needs to become more Boost-like #25.

Could you please link some resources/pointers on the convention for tests in Boost libraries?

**Comment by ckormanyos** [comment]
Hi @sinandredemption 

>> figure out how i broke and how to fix 10-byte `long double`.

> a way I can reproduce the issue on my system (for debugging)?

You need a GCC compiler running on *nix for that. On my desktop, I simply use the Windows Subsystem for LINUX to do a bunch of cross-over work.

> link some resources/pointers on the convention for tests in Boost libraries

It is essential to have a formally correct `number`backend. That is sort of the _entrance_ _requirement_ for moving forward, as I have in my branch.

The best form of guidance on the tests I have on this at the moment are those tests recommended by @jzmaddock. If you check out the `qd` branch of Boost.Multiprecision, you will find the original draft of `quad_double` created as a wrapper library. This work was done by John about a year and a half ago. In that branch, you will find that John has implemented an entire _QD_ test suite in the so-called _JAM_-file for testing.

For instance, in that work, _QD_ function tests are in the JAM-file in places such as [here](https://github.com/boostorg/multiprecision/blob/cf9eb73f0af24a544b3ab2a45a6863703aa3b3e6/test/Jamfile.v2#L309) for a numerous tests of [elementary transcendental functions](https://github.com/boostorg/multiprecision/blob/cf9eb73f0af24a544b3ab2a45a6863703aa3b3e6/test/Jamfile.v2#L255).

As soon as we agree on a backend implementation, I can start churing out the tests and adaptingf for the _real_ Boost test machine...

**Comment by ckormanyos** [comment]
Hi @sinandredemption allow me to describe some other things that I personally tend to do prior to cranking up the entire big Boost.Multiprecision test machine.

Consider the modified version of [test_sqrt.cpp](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_backend_reqs/test/test_sqrt.cpp). As we move forward, we will be preparing such files with a to-be-invented compiler switch similar to `TEST_CPP_DOUBLE_FLOAT`.

From the JAM-file, we see that this file will be tested for all floating-point backends.

You can get a preview of how this file is expected to pan out in MSVC without running the entire Boost test. Simply take the content of that file. Go to any one of your MSVC projects and entirely overwrite your single main file with that one. Define at the top of this file `TEST_CPP_DOUBLE_FLOAT`. Ensure that Boost.Multiprecision's _test_ directory is included in the list of compiler include paths and build and run. Do this, for instance while including my branch which is wrapped as a `number`backend.

When doing this, for instance, in my branch, I found 2 errors:

```
Max error was: 0
In function: void __cdecl test<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<float>,1>>(void)
C:\Users\User\Documents\Ks\PC_Software\Test\test.cpp:195 Failed predicate: (boost::math::isfinite)(sqrt((std::numeric_limits<T>::max)()))
Max error was: 0
In function: void __cdecl test<class boost::multiprecision::number<class boost::multiprecision::backends::cpp_double_float<double>,1>>(void)C:\Users\User\Documents\Ks\PC_Software\Test\test.cpp:195 Failed predicate: (boost::math::isfinite)(sqrt((std::numeric_limits<T>::max)()))
2 errors detected.
```

So all the numeric test passed, but simple problems with max, inf, etc.

You can _manually_ go through many Boost tests prior to running the whole test system and increase the odds that problems are detected early in a controlled MSVC environment this way.

**Comment by ckormanyos** [comment]
Hi @sinandredemption and @cosurgi
Preliminary decision is: Go for `quad_float` as a separate entity with its complete own header and algorithm(s).

Related to #14

**Comment by sinandredemption** [comment]
I am closing this issue as it has been decided that the way forward would be to work on `quad_float` without using a cascade construction.
