### ISSUE TITLE
double_float needs to use NaN and inf

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#33]
The `double_float` template class needs to make use of NaN and infinitiy. There are some basic behaviors needed for a Boost.Multiprecision backend. These include:
- Handle NaNs
- Division finite/0 gives infinity.
- Support the concept of negative infinity.
- Negative infinitiy should test less than 0.
- Infinity should test greater than 0.
- Probably some more characteristics we find/remember along the way...

**Comment by sinandredemption** [comment]
Some progress on the issue is made in [this commit](https://github.com/BoostGSoC21/multiprecision/commit/2a91e292dab33db81bcbc8bbe97f79199fc100ac).

**Comment by ckormanyos** [comment]
Hi @sinandredemption your changes in the backend reqs branch are going green on CI (after a bit of back and forth from my side).

I will report fully in #34

For me, this means that `double_float` is fully viable as a Boost backend candidate --- in early stages --- but having loads of potential.

Full speed ahead on any plans you have to refine the backend reqs branch or draft new stuff for `quad_float`.

**Comment by ckormanyos** [comment]
Please note that I commented out a few inf/NaN/construct-from-enum tests in `test_arithmetic_df.cpp` in the associated header file. We can refine the `cpp_double_float` backend relatively easily to accomidate for these as we move forward.

**Comment by ckormanyos** [comment]
This is done. Some tweaking and corrections are being and probably will be found as progress in CI / use in special functions continues. These can be tracked as they are found.

Time to close this issue.
