### ISSUE TITLE
double_float confusing precision loss in calculations

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#35]
Based on the very, very preliminary first wrap of  `cpp_double_float` as a multiprecision backend, I tried out some numerical calculations with this data type in Boost.Math.

I find large precision loss in relatively straightforward calculations of `tgamma(1/2)` and `cyl_bessl_j(2, 345/100)`. See the code below. The Gamma function calculation loses about 6 decimal digits of precision whereas the Bessel function calculation loses about 11 decimal digits of precision.

I wonder if the lossy bit(s) mentioned in #26 and briefly encountered in other posts might accumulate throughout a calculation or if there is some other problem going on.

```
#include <iomanip>
#include <iostream>

#include <boost/math/constants/constants.hpp>
#include <boost/math/special_functions/bessel.hpp>
#include <boost/math/special_functions/gamma.hpp>
#include <boost/multiprecision/cpp_double_float.hpp>
#include <boost/multiprecision/cpp_bin_float.hpp>

template<typename MpFloatType>
void represent_cyl_bessel_j()
{
   std::cout << std::endl << "represent_cyl_bessel_j" << std::endl;

   using float_type    = MpFloatType;

   const float_type b    = boost::math::cyl_bessel_j(2, float_type(345) / 100);
   const float_type ctrl("0.46452112540537213897844513503678");

   const float_type delta = fabs(1 - (b / ctrl));

   // N[BesselJ[2, 345/100], 32]
   // 0.46452112540537213897844513503678
   std::cout << std::setprecision(std::numeric_limits<float_type>::digits10) << b    << std::endl;
   std::cout << std::setprecision(std::numeric_limits<float_type>::digits10) << ctrl << std::endl;
   std::cout << std::scientific << std::setprecision(4) << delta << std::endl;
}

template<typename MpFloatType>
void represent_tgamma_half()
{
   std::cout << std::endl << "represent_tgamma_half" << std::endl;

   using float_type    = MpFloatType;

   const float_type g    = boost::math::tgamma(float_type(0.5F));
   const float_type ctrl = sqrt(boost::math::constants::pi<float_type>());

   const float_type delta = fabs(1 - (g / ctrl));

   // 1.77245385090551602729816748334115
   std::cout << std::setprecision(std::numeric_limits<float_type>::digits10) << g    << std::endl;
   std::cout << std::setprecision(std::numeric_limits<float_type>::digits10) << ctrl << std::endl;
   std::cout << std::scientific << std::setprecision(4) << delta << std::endl;
}

int main()
{
   using double_float_type = boost::multiprecision::number<boost::multiprecision::backends::cpp_double_float<double>, boost::multiprecision::et_off>;
   using bin_float_type    = boost::multiprecision::number<boost::multiprecision::cpp_bin_float<std::numeric_limits<double_float_type>::digits10>, boost::multiprecision::et_off>;

  represent_tgamma_half<double_float_type>();
  represent_tgamma_half<bin_float_type>();

  represent_cyl_bessel_j<double_float_type>();
  represent_cyl_bessel_j<bin_float_type>();
}
```

**Comment by sinandredemption** [comment]
I think one way to move forward with this would be to compare the behaviour with other double float implementations (e.g. that of QD package, or @ckormanyos legacy work).

**Comment by ckormanyos** [comment]
> one way to move forward with this would be to compare the behaviour with other double float implementations (e.g. that of QD package, or @ckormanyos legacy work)

Indeed, I was thinking something similar. It will take a bit of time, but I will attempt to wrap one of these legacy programming artifacts for use with Boost.Math and put it into Boost.Math calculations.

**Comment by ckormanyos** [comment]
The problem on `cyl_bessel_j` was simply the incorrect value of the `epsilon()` member of `std::numeric_limits`. See also issues #21 and #24.

I will make some quick fix(es), albeit not `constexpr` correct ASAP.

**Comment by sinandredemption** [comment]
> I will make some quick fix(es), albeit not constexpr correct ASAP.

Thank you, @ckormanyos . Please know that I can come in any time to help or continue where you left off.

**Comment by ckormanyos** [comment]
> Please know that I can come in any time to help or continue where you left off.

Thanks @sinandredemption the tests on the branch successfully cycled.

Could you please check your last changes as well. I was fumbling around a bit on the pull and merge. Please continue at will!

**Comment by sinandredemption** [comment]
> Could you please check your last changes as well. I was fumbling around a bit on the pull and merge. Please continue at will!

@ckormanyos Please do check [this commit](https://github.com/BoostGSoC21/multiprecision/commit/c82872410c977fbd7ea5290b3c2f60d78e4efbcf), and let me know your thoughts, especially on [these changes](https://github.com/BoostGSoC21/multiprecision/commit/c82872410c977fbd7ea5290b3c2f60d78e4efbcf#diff-bb9459c4a1f6866e23101b1428b9f6a910b63310156b202b3946d414fcb92071R888) I have made to `std::numeric_limits<>`.

I was wondering if the standard Boost.Multiprecision tests contain a test suite for testing `std::numeric_limits<>` specialization of a class; that would be convenient at the moment. If not, we might have to write our own tests to rigorously establish the values specialized in `std::numeric_limits<>`

**Comment by ckormanyos** [comment]
> @ckormanyos Please do check this commit, and let me know your thoughts, especially on these changes I have made to `std::numeric_limits<>`

Good job. I tweaked a bit further, made a PR, CI got green and merged to develop of the fork. Some of the properness of `constexpr` correctness will be on the to-do list, but that's OK for now. Good job!

> wondering if the standard Boost.Multiprecision tests contain a test suite for testing `std::numeric_limits<>` specialization of a class; that would be convenient at the moment. If not, we might have to write our own tests to rigorously establish the values specialized in `std::numeric_limits<>`.

Good question. I don't actually recall. A lot of that stuff is testd parasitically in the full battery of tests.

The idea right now is to try out a few tests manually and in a few quick, definitive steps move toward the full battery of Boost.Multiprecision tests. At the moment, we trust the tests rather well. So if we can hammer `cpp_double_float<T>` with all the tests, then we are in pretty good shape.

I will soon take a closer look as some elementray transcendental functions such as `exp`, `log`, trig functions, as I suspect some of these synthesized versions might not be so great in tóur modest precision range(s). These _might_ be what's hacking off 5 decimal digits of precision on `tgamma(1/2)`. So we might need some special care on some elem trancendentals, especially `log`.

After that, I'll look into #25 and make a dedicated double-float test suite in the formal _Boost_-_way_.

@sinandredemption

**Comment by ckormanyos** [comment]
Note: Look into precision loss on `tgamma(1/2)`. Is it expected? Why? Why not? Verify elementary transcendentals, since there is not much going on in that calculation other than coefficient expansion followed by a few elementary transcendental calculations.

**Comment by ckormanyos** [comment]
This is mostly fixed by #40. The cases of `cpp_double_float<double>` for 8-byte double and `cpp_double_float<boost::multiprecision::float128>` work fine with `tgamma(1/2)` and a Bessel function calculation.

There are, however, still precision problem(s) with `cpp_double_float<float>` for 4-byte `float`. Keep this issue open for the moment while investigating this phenomenon.

**Comment by ckormanyos** [comment]
> Keep this issue open for the moment while investigating this phenomenon.

More has been learned. When investigating `cpp_double_float<T>`, there is different behavior on GCC when compiling/running with/without the presence of quadmath. The could be a strong indication that the operator/constructor resolutions are not quite right when resolving `boost::math::float128` from other built-in floating-point types.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Could this issue be related to the bug that was fixed today [here](https://github.com/BoostGSoC21/multiprecision/commit/3db126752be3ffa21b6aca6a5426f0e4b4b8e9e0)?

Note that this bug would have been noticed earlier if the home-grown tests for double-float were also included in the CI.

**Comment by ckormanyos** [comment]
> Could this issue be related to the bug that was fixed today

Hi @sinandredemption I had hoped for that, but unfortunately this strange precision loss persists on GCC. I really need to dive into constructors and the code of Boost.Math to figure out why?

> this bug would have been noticed earlier if the home-grown tests for double-float were also included in the CI

I thought we had included these tests, albeit with decreased exponent range. These tests are listed in the `df_qf` test suite of the [jamfile](https://github.com/BoostGSoC21/multiprecision/blob/7c42ce5884770ab200a677756444371de347cebd/test/Jamfile.v2#L118). I do not know if we missed something along the way, maybe a distinct posibility.

**Comment by ckormanyos** [comment]
Just upped the tolerance 1 more bit when hammering 128-bit multiplications. TBD: Investigate and if/why/should-be/is-explainable regarding precision loss.

**Comment by ckormanyos** [comment]
We need to go back and study the original Briggs (adopted by Shoup) work. This is in the `q_float` repo (reproduced from my own work) in this fork way back from the start.

Cc: @sinandredemption

**Comment by ckormanyos** [comment]
This will be handled in #136 
Cc: @sinandredemption
