### ISSUE TITLE
double_float make specializations for exp/log at various precision(s)

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#38]
It probably makes sense to create specialized versions of elementary `exp` and `log` functions at precisions such as 15-decimal-digit `double`, 6-decimal-digit `float`, etc.

The classic mehtod(s) consider Pade for `exp` and one Newton-Raphson step for `log`.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Would you please elaborate on why we need specialized version of elementary functions for built-in _native_ types? I could be mistaken, but perhaps you mean specialized version of `cpp_double_float<>` types?

**Comment by ckormanyos** [comment]
> elaborate on why we need specialized version of elementary functions

Maybe there is a better way, but recall that, for instance, `cpp_double_float<double>` is actually composed of two elements of type built-in `double`. The standard `double exp(double)` function will only give half the required precision for the double-double type.

Furthermore, we can not assume that `double` is twice as wide as `float`, nor make any assumptions about the actual widths of these except common _guesses_. In addition, we can not assume that there is a `float128` hanging around in the system.

All this forces us to make clever fast approximations for some simple elementary functions. Otherwise, we will be using the stock-versions of the synthesized `number` backend transcendentals, which are not optimized for the use case.

A common case would look something like what I did in my (comletely unrelated) software-synthesized `soft_double` class [here](https://github.com/ckormanyos/soft_double/blob/6f1c3c102487a5f09ef3fa1377babcb0ec70cfe5/math/softfloat/soft_double.h#L1333). But that particular Pade approximation after argument scaling was good for about 15 decimal digits. In our case here, we might select 3 approximation range(s) such as up to 13 decimal digits, 14 through 32 decimal digits, and 33 through 66 decimal digits, each range having more coefficients and a separate enaboed-if specialization.

**Comment by sinandredemption** [comment]
> Otherwise, we will be using the stock-versions of the synthesized number backend transcendentals, which are not optimized for the use case.

Oh, got it now :)
