### ISSUE TITLE
double float implement and test add/sub/mul/div

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#5]

**Comment by ckormanyos** [comment]
Hi @sinandredemption and @cosurgi this might be interesting for algorithms with `double_float`.

I had forgotten, but apparently in 2005 I make a class called `q_float` which has a misleading name, but was actually a `double_double`.

I placed this project in an examples folder [here](https://github.com/BoostGSoC21/multiprecision/tree/gsoc2021_double_float_chris_modify_and_test/example/q_float)

Anyway, the project is not perfect, it is a bit outdated. I did, however, apparently modify and update this in 2020 a bit.

The project has working implementations of add, sub, mul, div, sqrt, frexp, trig, exp, and more functions. It might provide good example character for the implementation in this year's GSoC21 for the basic `double_float` template class.

For instance, unary add, sub, mul, div can be found [here for about 300 lines](https://github.com/BoostGSoC21/multiprecision/blob/cfbffdb935c21c5930c02e284c61ee8585781937/example/q_float/q_float/q_float.h#L129).

I put in some tests using control from Boost.Multiprecision. The performance can probably be tweaked and it's only for double-double. But good stuff for studies on the algos.

**Comment by sinandredemption** [comment]
Thank you for this, Chris.

I especially like the string I/O methods wr_string() and rd_string(). They might be handy when I finally code the standard-compliant I/O functions for cpp_double_float<>.

**Comment by ckormanyos** [comment]
After update of `double_float`, i find add/sub/mul ok, but for some reason still encounter problems with div. It might be the test code. It could, however, be in the header(s). i will investigate.

**Comment by ckormanyos** [comment]
I also notice that certain constructors of `double_float` are ambiguous. Also the assignment operator from `std::string` should probably not be miplemented with reliance on string construction being potentially better instead.

**Comment by ckormanyos** [comment]
Hi @sinandredemption I can straighten out the constructor ambiguities and string constructor confusion. You can see some of these problems on GCC in the latest CI run [here](https://github.com/BoostGSoC21/multiprecision/actions).

**Comment by sinandredemption** [comment]
> I also notice that certain constructors of `double_float` are ambiguous.

I am aware of some of the problems with the constructors. I will fix in the next update as many as I notice.

**Comment by ckormanyos** [comment]
> some of the problems with the constructors

That will be very useful. It can be challenging, but really add a lot to the quality and applicability of a numerical type to get constructors and operators somewhat, let's say, correct. This means correct in the sense that the type behaves closely to the behavior of a built-in type --- albeit a rather subjective definition of _correct_.

It can be help ful to look at a working, modern example.

One of the simpler working exemplary numeric types I have in a published form is the `soft_double` class found [here](https://github.com/ckormanyos/soft_double).

It has a rather minimal, yet complete set of [constructors](https://github.com/ckormanyos/soft_double/blob/6f1c3c102487a5f09ef3fa1377babcb0ec70cfe5/math/softfloat/soft_double.h#L394) and [operators](https://github.com/ckormanyos/soft_double/blob/6f1c3c102487a5f09ef3fa1377babcb0ec70cfe5/math/softfloat/soft_double.h#L226) making it behave _normally_.

**Comment by ckormanyos** [comment]
Hi @sinandredemption in #8 we still find that division seems to be broken. The constructors and casts, however are coming along nicely.

Merge progress to develop OK.

CC to @cosurgi

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Apologies for not mentioning you in [this comment](https://github.com/BoostGSoC21/multiprecision/pull/8#commitcomment-52539493) where I address the div problem. It seems the div problem is an I/O problem, and not a algorithmic one, and increasing the output precision solves it. If possible, please do try [this minor change](https://github.com/BoostGSoC21/multiprecision/blob/1d8228b78c7b48e831021ad35add95f5bcb64e21/test/test_arithmetic_cpp_double_float.cpp#L123) as a temporary fix.

**Comment by ckormanyos** [comment]
> ...the div problem is an I/O problem

Looking good. Thanks @sinandredemption .

Tests are cycling in CI on my branch.

You might also like the improved `pow10` helper function using the efficient so-called _ladder_ _method_ [here](https://github.com/BoostGSoC21/multiprecision/blob/886a35b1dd9f182585c5befac1b3c0885d27c6ec/include/boost/multiprecision/cpp_double_float.hpp#L619).

**Comment by ckormanyos** [comment]
If nothing else comes up soon on this, we have add/sub/mul/div and can close this issue.

**Comment by ckormanyos** [comment]
Closing since add/sub/mul/div are implemented in `double_float`.

Further issues such as sporadic single-bit errors in tolerances of certain test cases, etc. to be handled in other issues.
