### ISSUE TITLE
quad_float implement numeric_limits

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#50]

**Comment by ckormanyos** [comment]
See #65 for the latest draft of limits for quad-float

**Comment by sinandredemption** [comment]
The value of `digits10` has been updated in #66 to `int(float(digits - 1) * 0.301F) - 1;` in #66, [in this commit](https://github.com/BoostGSoC21/multiprecision/pull/66/commits/b14b33959ff0b0b493dca4bd891dd33c62b740bc) ([why?](https://github.com/BoostGSoC21/multiprecision/pull/66#issuecomment-894616444)).

**Comment by sinandredemption** [comment]
Question: What is the denorm_style for `cpp_double_float<>` and `cpp_quad_float<>`? Intuitively, both classes should support subnormal arithmetic. But this needs to either be proven or rigorously tested.

@ckormanyos @cosurgi

**Comment by cosurgi** [comment]
In my experience denorm calculations are more of a hindrance than being useful. Maybe add them later, but for now I tend to prefer to say that we do not support denorm values.

Copying denorm values from the base float type would indeed require some more careful considerations of the proofs for the algorithms. It is an interesting avenue of thought, but presently I guess we lack time for that.

**Comment by ckormanyos** [comment]
@sinandredemption in your opinion can this issue be closed? Potential tuning if needed can open bug-style future issues.

Cc: @cosurgi

**Comment by ckormanyos** [comment]
Closing based on preliminary successful implementation from @sinandredemption

Cc: @cosurgi
