### ISSUE TITLE
quad_float implement Boost-backend funcs eval_fabs/frexp/ldexp/floor/ceil/sqrt

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#51]
These are the most basic functions. Original work from John's qd branch and also some methods from `cpp_double_float` can be extended/adapter.

**Comment by ckormanyos** [comment]
Hi @sinandredemption in your modern work, where do we stand on add/sub/mul/div for `cpp_quad_float<T>`?

It looks pretty close. Can I begin starting the backend reqs for Boost-ification for quad-float now or soon?

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

We might have to wait a couple of days for that.

I am currently working on multiplication procedure, and division should be pretty easy once the other three operators are up and running. After that, you can begin working on Boost-ification of `cpp_quad_float` while I will continue to add specializations for these arithmetic functions or work on other things.

**Comment by ckormanyos** [comment]
> wait a couple of days for that

Understood. No rush. Give me a ping when it's ready or ready enough...

Then I will start trying to Boost-ify quad-float

**Comment by ckormanyos** [comment]
> will start trying to Boost-ify quad-float

Hi @sinandredemption is it OK for me to start this activity no in your opinion? With the good work in other branch(es) I feel like we are at a good point for this now.

Thoughts?

**Comment by ckormanyos** [comment]
> start this activity

It seems like you already started a bunch of it. I will take a try for limits, `frexp`, `ldexp`. Those are straightforward. Although we might have a few discussions about limits.

For sqrt, I have a few ideas. I think a good one might be to start with reciprocal square root from the std-lib function on the first built-in floating-point type, subsequently perform two steps of Newton iteration, then invert. We can see how that goes.

I expect rather good results for log() and exp(), although these might need tuning for `cpp_quad_float<float>` which has fewer digits. The others, I expect to simply _take off the rack_ of default-ops as a first cut at it.

**Comment by sinandredemption** [comment]
Hello @ckormanyos
Apologies for the apparently late replies. I was/am writing a report on my experiments with `cpp_quad_float<>` which I will soon present.

> Thoughts?

Yes, please, by all means go ahead. Please note that the underlying representation for `cpp_quad_float<>` is a `std::tuple`. With that in mind, I don't imagine that the implementations of `eval_*` routines will be much different than versions of `cpp_double_float<>` adaptation.

**Comment by ckormanyos** [comment]
> by all means go ahead

Will do. I can take a shot at the arithmetic tests as well.

I suspect I will need your help (from your branch) with limits. I seem to be struggling now with the min/max parameters of limits. I will contact you guys for advice on these (but I see your newest draft also has min/max for quad too). I'll be in touch on that.

Cc: @sinandredemption and @cosurgi

**Comment by sinandredemption** [comment]
> but I see your newest draft also has min/max for quad too

That is taken from `cpp_double_float<>`

**Comment by ckormanyos** [comment]
Boost-ification for both `cpp_double_float` as well as (based on the push of #65) `cpp_quad_float` is established in a rudimentary way. This uses jam/Ci/YAML in the semi-normal way.

For me, the start represented in #65 is a strong enough to close this issue. Follow-up `eval_whatever` refinements and more CI testing in subsequent issues.

Cc: @sinandredemption and @cosurgi
