### ISSUE TITLE
quad_float setup Boost-like CI resting with jamfile

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#52]

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Maybe you could add the two test files from the [latest commit](https://github.com/BoostGSoC21/multiprecision/commit/b8052d2c0c7e7d5cdda2138f4f1fa6698bdf8052) to CI? That would be very helpful.

Thanks!

**Comment by ckormanyos** [comment]
> Maybe you could add the two test files ... to CI?

Hi Fahad. I like that direction. From here on forward, I will only be adding files to CI that actually test the Boost-ified, wrapped type. Your files, although excellent in concept, test the _naked_ `cpp_quad_float` backend.

@sinandredemption if in any way possible, also with my help if needed, could we please test the type(s):

```
boost::multiprecision::number<boost::multiprecision::backends::cpp_quad_float<T>, ExprTemplates>
```

You can take a simple example from the arithmetic tests of the double-float case in develop. The quad-float case should be almost identical.

**Comment by ckormanyos** [comment]
The test mechanism for both `cpp_double_float` as well as (based on the push of #65) `cpp_quad_float` is established in a rudimentary way. This uses jam/Ci/YAML in the semi-normal way.

For me, this is a strong enough start to close this issue.

Cc: @sinandredemption and @cosurgi
