### ISSUE TITLE
double_float how to write homegrown arithmetic tests

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#59]
In double-float (and probably quad-float) there is an underlying desire to hammer the arithmetic tests with millions upon millions of test cases for instantiation of the composite type(s) with `float`, `double` and `long` `double`. The purpose of these tests is generally low-level arithmetic verification through intensive testing of operations add/sub/mul/div/sqrt for the composite type with as low tolerance(s) as possible.

Over the course of the development, there have been several varying versions of the file `test_cpp_double_float_arithmetic.cpp` located [here](https://github.com/BoostGSoC21/multiprecision/blob/develop/test/test_cpp_double_float_arithmetic.cpp) as well as in other popular branches.

The question arises: How do we write this file? How do we generate reliable test data? Which multiple-precision type (and how is it constructed) can be used to provide reliable control values for the results of add/sub/mul/div/sqrt?

**Comment by sinandredemption** [comment]
IMHO, the following (random) points make sense:
- The (general) test cases must have the exponent of the numbers uniformly distributed over `[min_exponent, max_exponent]`. This is akin to a log-uniform distribution
- A few zeroes thrown here and there don't hurt

We can begin to structure the test along the following lines:
- One series of tests for verifying correctness of algos given **valid** data.
- One series of tests for verifying predictability of behavior given **invalid** data (e.g. handling of infinities and NaNs)

Please excuse me for making seemingly random points.

**Comment by ckormanyos** [comment]
Good ideas @sinandredemption thank you.

Based on the very successful results on #21, I will integrate your points above with the tests as running in our recent PRs. As mentioned also in #21, I will set up a nightly CI as we progress forward.

**Comment by ckormanyos** [comment]
As soon as these ideas are integrated in the tests, and everything is pulled onto develop (which might all take a day or so...), i'll close this issue at that time.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

I find the log-uniform RNG used in the old arithmetic test a bit more exhaustive than string-based float RNGs, especially for stress testing things in extreme cases. The [line of particular interest](https://github.com/BoostGSoC21/multiprecision/blob/3483a5e76c0237df9b32ddff57eeb73350528acf/test/test_cpp_double_float_arithmetic_old.cpp#L71) is:

`random_float = ldexp(uniform_real<FloatingPointType>(), rand_in_range(min_exponent, max_exponent));`

Please let me know your thoughts on this.

**Comment by ckormanyos** [comment]
> Please let me know your thoughts on this.

If you can get the tests working and clean within the context of using `boost::multiprecision::number<cpp_double_float<T>>>`, then I am happy to go that way. In fact, the string creation is very slow as I have implemented it and I would, in fact, be quite interested if you could improve on that.

Cc: @sinandredemption

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Please do check the RNG for `cpp_quad_float` [here](https://github.com/BoostGSoC21/multiprecision/blob/36683defd59751d9ed71ad9daac46b46d7fa5b43/test/test_cpp_quad_float_constructors.cpp#L59). It produces values uniformly over the complete range representable by `cpp_quad_float`, so I think it should theoretically be excellent for rigorous tests.

It does not use the most elegant way ever, so please feel to modify/criticize.

**Comment by ckormanyos** [comment]
> check the RNG for `cpp_quad_float`

Looks pretty good to me. If it works for the tests, then we can go with that. Thanks @sinandredemption

**Comment by ckormanyos** [comment]
There is a good working model in [test_cpp_quad_float_constructors.cpp](https://github.com/BoostGSoC21/multiprecision/blob/develop/test/test_cpp_quad_float_constructors.cpp) that can be used as a template for generating uniform random test data. This model can be used for other double/quad-float homegrown arithmetic tests going beyond those already present in the Multiprecision test suite(s).

Close this issue now.
