### ISSUE TITLE
double_float constructors and casts

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#6]
This issue tracks progress and refinements on constructors and cast operators for the `double_float` class.

**Comment by ckormanyos** [comment]
Hi @sinandredemption I have refined your constructors and taken the liberty to merge these refinements to your branch.

I also activated CI on your branch and activated both CI as well as status checks on develop branch. A recent PR #8 is checking these.

**Comment by sinandredemption** [comment]
Thank you for this, @ckormanyos .
I have further refined the constructors in the latest commit [(see this)](https://github.com/BoostGSoC21/multiprecision/blob/2b53ed9924ada6237164e85f7321e0a7565e5a62/include/boost/multiprecision/cpp_double_float.hpp#L181)

However, it seems to me that cpp_double_float<float> doesn't still mimic the behaviour of double for construction from an 64-bit integer. Is this something we should be concerned about? Or is the cast from a 64-bit integer to a double implementation defined anyway, so we shouldn't bother (as long as cpp_double_float<float> correctly parses the first 52 bits)?

**Comment by ckormanyos** [comment]
> further refined the constructors in the latest commit

Good job! I will check out this.

> it seems to me that `cpp_double_float` doesn't still mimic the behaviour of double for construction from an 64-bit integer. Is this something we should be concerned about?

These are often tricky questions. In many systems, the standard implementation of built-in `double` has 53 bits precision. As such, this will not be able to, let's say, _hold_ the full precision of `std::uint64_t`, having, in fact more bits than `double`.

For this reason, some systems might be rounding when converting from `std::uint64_t` to built-in `double`.

Your implementation of `double_float`, when instantiated for 64-bit built-in `double` will, in fact, be able to _hold_ all the digits of any initialization from built-in `std::uint64_t` without precision loss or the need to round. I could imagine this might cause different phenomena than might be expected.

I do not know if this is going on or exactly what you mean. I also think that the constructor situation is not yet an entirely full set of the expected constructore needed for the type to mimic closely the behavior of a built-in type...

... So, ... For all of these reasons, I will be helping to review the constructors and casts and might add some slight revisions, communicating these in the posts, as we move forward.

I encourage you also to keep going on these steps as well.

**Comment by sinandredemption** [comment]
You are right in saying this:
> Your implementation of double_float, when instantiated for 64-bit built-in double will, in fact, be able to hold all the digits of any initialization from built-in std::uint64_t without precision loss or the need to round.

Apologies if I wasn't clear enough. I was referring to double_float instantiated for _32-bit float_, which can in theory only hold 46 (?) bits of precision. And the rounding modes used by cpp_double_float<_float_> currently do _not_ mimic those of built-in double.

My question is precisely this: Is there a **standard** (maybe IEE-754 compliant) rounding behaviour when converting from `int64_t` to `double` that we should care about? Or is this left to the implementation?

**Comment by ckormanyos** [comment]
> Is there a standard (maybe IEE-754 compliant) rounding behaviour when converting from int64_t to double that we should care about? Or is this left to the implementation?

Great question.

Yes. There are several different rounding modes supported. I can't, at the moment, recall if these are or are not explicitly specified in IEEE-754:2008 itself.

But basically the story goes like this. You select one specific rounding mode. A good choice is to take the one that is found on some or all of your most common target systems. You then mimic this rounding mode as best as possible.

Along the way, your (to come later) specialization of `std::numeric_limits` for your `double_float` type should properly report which exact rounding mode has been selsected.

The luxury model of this design is to create a namespace-sprcific enumerated class listing the kinds of supported rounding modes that you wish to emulate. This type can subsequently be used as an additional defaulted template parameter on `double_float`.

This luxury leads to a bunch of a lot of internal coding and `enable-if`-ing. And in my opinion, `double_float` does not gain a lot of added value for this. So I personally would support 1 and only 1 rounging mode and report this in the future numeric limits of the class(es).

**Comment by ckormanyos** [comment]
Another note...

When writing a numeric type, it seems to really pay off to get right constructors/casts, elementary arithmetic and comparison operators, and sqrt, frexp, ldexp, sign, and I/O streaming, and a specialization of `std::numeric_limtis`

As soon as these are tested well and working, writing the higher elementary functions and even hooking the type into Boost.Multirpecision and subsequently Boost.Math is a pleasure, simple and icing on the cake.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Please do check [this commit](https://github.com/BoostGSoC21/multiprecision/commit/0a09d691abdf084c1f5d455d7a51278091b94ebe), in which I have refactored the constructor code and added rigorous tests for constructors from integral types (tests for constructor from string is next on my TODO list).

Please do tell me if I can add something to the constructors or further refine things.

**Comment by ckormanyos** [comment]
>  or further refine things

Great job @sinandredemption!

Here are a few review comments.

These represent basically a few design preferences that I might suggest. Now please bear in mind that these are very slight design preferences, but preferences that I usually use myself in a host of numeric types. They have always led to good results when used consistently by me in most situations.

1. On the constructors, there will be some work to enable C++11 (and in a second step C++14) `constexpr` to most if not all the constructors. This will facilitate compile-time assessment of double-float values. I can and will assist with this activity at a later time.
2. I will investigate the construction from unsigned integral type and see if it can be simplified and/or _maybe_ even C++11 `constexpr`-ified.
3. There are some other design elements. In your arithmetic operators, you emphasize binary arithmetic. I notice that your algorithms for add/sub/mul/div are implemented within the binary arithmetic operations such as `double_float + other`, `double_float - other`, etc. This is OK. I prefer, however, to implement the algorithms within the unary arithmetic operations such as `double_float += other`, `double_float -= other`, etc. After doing this, I find a slight typing simplicity because all other non-class binary arithmetic can be easily implemented in terms of these primitives. This may also be ever so slightly more efficient and clear over the course of all arithmetic operations because I think the numbers of temporaries might be decreased, even though the compiler optimizes most of those away anyway.
4. Your comparison operators seem to be too rich in detail. There is a standard procedure to implement two comparison operations algorithmically only. Then derive the remaining 4 others in terms of these. This reduces the opportunity of unwanted error and code keeps code upkeep to a minimum.
5. At several places, you are using the function `std::abs` from the STL's `<algorithm>`. When floating-point types are concerned, I prefer to use the double line `using std::fabs;` and then simply use standalone call to `fabs`. For non-built-in types, ADL will find the needed function and `fabs` is in general more clean and clear than `std::abs` for built-in floating-point types.

This is all rahter trivial stuff and none of it is really mandatory. I do think it would be nice, nonetheless, if you considered some of these suggestions. This iwll help me, for instance with future typing when creating the non-class inline functions for binary arithmetic and comparison, orhelp you if you do these beacuse we can simply basically copy them from several one(s) of my existing examples.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

Thank you for your valuable suggestions. All of these points have been noted and you can expect all of these to be implemented over the next few commits.

**Comment by sinandredemption** [comment]
Hello @ckormanyos 

> implement the algorithms within the unary arithmetic operations

I am working on this. There seems to be one slight complication though (not specific to your advice).

The final result when a binary operation is performed on two different types should intuitively be of the type containing more detail. Hence the return type of binary arithmetic operators could be a compile-time conditional type.

Take the example of adding a cpp_double_float<float> to a double. Since the `double` type contains a few more bits of precision than `cpp_double_float<float>`, it makes sense that the return type of `operator+(cpp_double_float<float>, double)` be `double`.

Implementing return type of binary arithmetic operators as `std::conditional<more_precision_type_condition>::type` comes to my mind.

I request your comments/thoughts on this, since I'm not sure what the standard behavior (or the standard Boost.Multiprecision convention) is, for this matter.

**Comment by ckormanyos** [comment]
>  result when a binary operation is performed on two different types

This is an interesting design choice.

>  your comments/thoughts on this

At the first cut, let's keep it simple. Simply return the composite type.

Within the subroutine itself, construct the built-in type to the composite type and perform binary add/sub/mul/div in the usual way.

Non-member add/sub/mul/div operators (within the enclosing namespaces) could, then, be like below:

```
template<typename FloatingPointType>
cpp_double_float<FloatingPointType> operator+(cpp_double_float<FloatingPointType>, double);

template<typename FloatingPointType>
cpp_double_float<FloatingPointType> operator+(double, cpp_double_float<FloatingPointType>);
```

You _might_ also be able to reduce typing via successfully using `enable_if` on the built-in type to handle `float`, `double` and `long` `double`. I usually implement these non-member binary operators independently for built-in floating-point types and separately for built-in integral types.

Remember, ultimately this stuff will be wrapped yet again as a Boost.multiprecision backend. So we get more syntax helpers from that. We just need the basic _eval_ functions. So even after this, if we like to specialize a few of them for speed/size, tec. we can even still do that on the level just prior to wrap for Boost.
If we need some

**Comment by cosurgi** [comment]
something that I planned to write earlier, but somehow I forgot:

> Is there a standard (maybe IEE-754 compliant) rounding behaviour when converting from int64_t to double that we should care about? Or is this left to the implementation?

> For example, a cpp_double_float<float> wouldn't be able to always capture a 64-bit integer with a complete accuracy because of limited precision.

This is very similar to the situation in which Ariane 5 rocket [exploded](https://en.wikipedia.org/wiki/Ariane_5#Notable_launches) shortly after launch on 4 June 1996 (the explosion was caused by the conversion in opposite direction, from float to integer).

Therefore I think that we should stay on the safe side and:

*  for overflow by default throw an exception (best if message is meaningful).
* for loss of precision (some bits must be cut to fit in the target type) I think that throwing exception by default is
also the best solution.

But let user to configure the default behavior via whatever means are easier to use: template arguments or
compile defines, or policies, or anything else.

**Comment by sinandredemption** [comment]
Hello @cosurgi 

> This is very similar to the situation in which Ariane 5 rocket exploded shortly after launch on 4 June 1996 (the explosion was caused by the conversion in opposite direction, from float to integer).

Interesting read, thank you mentioning :)

> for overflow by default throw an exception (best if message is meaningful).

So I think we should throw an exception **only if** the number is larger than `std::numeric_limits<cpp_double_float<FloatingPointType>>::max()`. Through extensive testing, we can ensure in all other cases, the number represented by `cpp_double_float<>` is the nearest possible.

> But let user to configure the default behavior via whatever means are easier to use: template arguments or
compile defines, or policies, or anything else.

Yes. I am open to suggestions on this.

Best,
Fahad

**Comment by ckormanyos** [comment]
Hello @cosurgi and @sinandredemption I would like to have (at least in a configurable form) the ability to avoid all exceptions and not even require the `<exception>` header. I say this because of future potential uses of the `double_float` and `quad_float` class(es) in particular on bare-metal systems that lack exception throwing mechanisms.

So if at all possible, please make this kind of stuff also potentially configure-away-able

**Comment by sinandredemption** [comment]
> I would like to have (at least in a configurable form) the ability to avoid all exceptions and not even require the <exception> header

Since we won't be able to include even the `<exception>` header, it seems to me that compile defines are the way to go. However, I am still open to suggestions.

**Comment by cosurgi** [comment]
Yes, in such case the defines are the way to go.

**Comment by cosurgi** [comment]
> on bare-metal systems that lack exception throwing mechanisms.

In such case, how the bare-metal onboard flight computer will prevent rocket explosion? :)

**Comment by ckormanyos** [comment]
Done. Possible improvements and potential handle for quad-float `float128` to be done in other issues.
