### ISSUE TITLE
quad_float implement and test add/mul/sub/div

### ISSUE THREAD

**Issue by sinandredemption** [BoostGSoC21/multiprecision#62]
This issue tracks the development and refinement of the basic arithmetic operators add/mul/sub/div of `cpp_quad_float<>`

I have the following goals in mind:
- **[DOING]** Basic arithmetic operators with arguments `cpp_quad_float<>` and `cpp_quad_float<>`
- **[PLANNED]** Basic arithmetic operators with arguments `cpp_quad_float<>` and `float_type` (native float)

Question: If time permits, should we specialize arithmetic operators for `cpp_double_float<>`?

**Comment by sinandredemption** [comment]
The basic arithmetic operators for two `cpp_quad_float<>`s are implemented in [this commit](https://github.com/BoostGSoC21/multiprecision/commit/b8052d2c0c7e7d5cdda2138f4f1fa6698bdf8052).

We still seem to have a problem with operator- (which is surprising because operator- uses operator+ in the backend).

**Comment by ckormanyos** [comment]
`cpp_quad_float` add/sub/mul/div/sqrt are working for `double`, `long` `double` and `boost::math::multiprecision::float128`. Curiously quad-float instantiated for `float` is not working, fades out on mul/div, as seen in #65

**Comment by sinandredemption** [comment]
> Curiously quad-float instantiated for float is not working

It seems that some of the problems are caused by limited exponent range in non-specialized string conversion. I am looking into the problem and hopefully will post a fix soon.

**Comment by ckormanyos** [comment]
That will be my mistake in the random string generator in the test code. I can fix as well

**Comment by sinandredemption** [comment]
> That will be my mistake

Not really. Seems like `boost::multiprecision::detail::convert_from_string()` is the problem.

**Comment by ckormanyos** [comment]
I'll take a look.

**Comment by sinandredemption** [comment]
Yes, please. Note also that I'm halfway through a fix.

**Comment by sinandredemption** [comment]
> This issue tracks the development and refinement of the basic arithmetic operators add/mul/sub/div of cpp_quad_float<>

The basic arithmetic operators have been implemented and fairly rigorously tested. I am closing this issue. Further developments will be tracked in #78

**Comment by ckormanyos** [comment]
Nice! Thanks Fahad!
