### ISSUE TITLE
double_float non-class binary arithmetic and comparison operators

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#7]
This issue tracks progress and refinement of non-class binary arithmetic operators and comparison operators for the `double_float` class.

**Comment by sinandredemption** [comment]
Hello,

Comparison operators have been implemented [(see this commit)](https://github.com/BoostGSoC21/multiprecision/commit/50d1ef94ae46b49ee587b7d5988f7d04c79e164c). Things turned out to be a little trickier than I initially guessed.

Comparison operators work by determining the type containing more detail at compile time, and then promoting the type with less detail to the type with more detail, and then comparing. Some minor complications arise while comparing unsigned types that are handled as well.

**Comment by ckormanyos** [comment]
Hi @sinandredemption is this issue in your opinion finished?

**Comment by sinandredemption** [comment]
@ckormanyos Not yet, I'm afraid.

Although the comparision operator part seems complete, I haven't implemented your suggestion to implement binary arithmetic operators using unary arithmetic operators.

**Comment by ckormanyos** [comment]
Thanks @sinandredemption no problem. i am simply trying to close as many issues as possible as we move forward. No hurries...

**Comment by ckormanyos** [comment]
I ended up switching these in my branch for the required Boost backend syntax including functions like `compare`, `eval_lt()`, etc.

But these still need proper handling of infinity and NaN.

**Comment by sinandredemption** [comment]
In the Boost-ified `cpp_double_float` class that @ckormanyos worked on, we seem to be lacking non-class comparison operators.

**Comment by ckormanyos** [comment]
> In the Boost-ified `cpp_double_float` class that @ckormanyos worked on, we seem to be lacking non-class comparison operators

Yes. Very astute observation @sinandredemption.

Perhaps I did not do such a _great_ job explaining the true `number` concept. But when we had started, it seemed like the more intuitive way to begin was for a standalone class. As we transition to a `number` backend, we do not need nearly so many namespace-specific functions.

These are not actually needed since the work of the `number` class synthezes these. You can make specializations of `eval_lt`, `eval_gt` and others to reproduce your work, but in the first syntactic draft, you do not need all of those operators that we have originally worked hard to get. I don't know exactly how you feel about this transition, but we can go at it in several steps.

You will also find that my class essentially kicked out the read/write of strings in favor of established Boost-tech.

**Comment by ckormanyos** [comment]
There is also another reason why I recommend to start with potentially extra work on a standalone implementation (and then migrate toward the `number` concept. The Boost testing via `number` wrapper can actually be quite tricky and non-intuitive. With that additional layer on top, it is often best to hammer our the draft of the class in an uninhibited fashion and migrate in a second step.

Anyway, this is how I have always proceeded with my own (sometimes non-published) Boost `number` backends. And it has always been successful method for me.

**Comment by sinandredemption** [comment]
@ckormanyos Given that such comparison operators are already implemented, it seems reasonable to close this issue.

**Comment by ckormanyos** [comment]
Finished with the backend requirements of #34
