### ISSUE TITLE
specialize arithmetic operators for native float types

### ISSUE THREAD

**Issue by sinandredemption** [BoostGSoC21/multiprecision#78]
Write specialized versions of arithmetic operators for native float type e.g. `operator+(cpp_quad_float<double>, double)`

Question: Should we also specialize arithmetic operators for `cpp_double_float` inside `cpp_quad_float` (e.g. `operator+(cpp_quad_float, cpp_double_float)`?

**Comment by ckormanyos** [comment]
> specialize arithmetic operators for ...

I think the best thing to do is to specialize `eval_add()`, `eval_sub()`, `eval_mul()`, `eval_div()`. If memory serves, there exists the possibility within the backend boilerplate code to _find_ specializations of these `eval_`- functions for various built-in types. A classic is multiplication with integral value.

In this case (of double float and quad float), add/sub/mul/div could all benefit from specializations with built-in floating-point types, as long as the built in type is less than or as wide as the constituent parts of the double-float or quad-float compound type.

Cc: @sinandredemption
