### ISSUE TITLE
quad_float full precision eval_sqrt

### ISSUE THREAD

**Issue by sinandredemption** [BoostGSoC21/multiprecision#80]
All of `cpp_quad_float`s arithmetic operators work well for `4 * digits` bits of precision (though there are rare exceptions which need more attention). However, the current `eval_sqrt()` procedure, maybe because of it's reliance of `cpp_double_float`, **loses two extra bits of precision**.

The relatively straightforward solution to this is to avoid dependence on `cpp_double_float` (as done in David Bailey's QD):

```
eval_sqrt(result, x) {
      result = (1.0F / std::sqrt(std::get<0>(x.crep())));

      quad_float_type h = x * 0.5F;

      result += ((quad_float_type(0.5F) - h * result * result) * result);
      result += ((quad_float_type(0.5F) - h * result * result) * result);
      result += ((quad_float_type(0.5F) - h * result * result) * result);

      result *= x;
}
```

I have personally tried this and it does seem to provide full `4 * digits` bits of precision. However, it might be slower, and can benefit from optimization (e.g. use the self-correcting nature of Newton's iterations).

Should we look into the optimizations after GSoC and make use of the extra precision it provides right now?
Thoughts?

CC: @ckormanyos @cosurgi

**Comment by cosurgi** [comment]
I agree, that correctness is more important than optimization. This helps establishing good tests. After GSoC we will have plenty of time to optimize this.

**Comment by ckormanyos** [comment]
> correctness is more important than optimization.

Agreed from my side as well.
