### ISSUE TITLE
 GSoC writeup report

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#92]

**Comment by ckormanyos** [comment]
This issue tracks any needed discussions regarding GSoC21 writeup/report.

Cc: @sinandredemption and @cosurgi

**Comment by sinandredemption** [comment]
I think the final report would benefit by including results from #67 in a meaningful and organized way.

**Comment by ckormanyos** [comment]
> report would benefit by including results from #67 in a meaningful and organized way

Agreed. I can run a few more tests/benchmarks and make some tables. But I do not think I'll have a chance in the shport time to establish the entire performance suite.

**Comment by ckormanyos** [comment]
> run a few more tests/benchmarks and make some tables.

Hi @sinandredemption my recent commit actually gets the performance test running `cpp_quad_float<double>` versus `cpp_bin_float` having a similar digit count.

Take a look at the results [here](https://github.com/BoostGSoC21/multiprecision/blob/2d3fe676f8dad9942ed2afe0ac72039f4cc6463e/performance/performance_test.cpp#L199). The entire modified performance test is within the same file. You can run locally and see how it goes... You need to add the performance directory to the standard include path.

**Comment by ckormanyos** [comment]
> look at the results

I had made some mistakes. It appears as though `cpp_quad_float<T>` is slightly faster in key areas than corresponding `cpp_bin_float`. But the differences are not as large as I had initially thought. Still all-in-all a very good result overall. Check out my modified benchmark(s). If need help, I can point you in the right direction.

So it appears as though quad-float has a lot of potential to be fast(er) than other backends in its region of precision.

Cc: @sinandredemption and @cosurgi

**Comment by sinandredemption** [comment]
Hello @ckormanyos @cosurgi 

Since the due date for GSoC wrap up is very near, and since I also need to set some time aside to write the final report, here's my current gameplan of wrapping up things:

- Include the new RNG in all tests
- ~Measure performance of both double-float and quad-float~
- ~Add the new constructor from long-long to `cpp_double_fp_backend`~
- ~General code cleanup and commenting~
- ~Complete performance tests for both double-float and quad-float~

I will add more things as I recall. Please feel free to suggest things I should do before the final wrap up for GSoC '21

**Comment by ckormanyos** [comment]
> due date for GSoC wrap up is very near, and since I also need to set some time aside to write the final report, here's my current gameplan of wrapping up things:

It sounds like a good, but honestly very optimistic, gameplan. When I think of getting all that to cycle in CI, it seems like almost too optimistic...

> Include the new RNG in all tests

This is optional not required. We can postpone till post GSoC since we have something sensible running now.

> Measure performance of both double-float and quad-float

I would restrict these perf marks to `cpp_double_double` and `cpp_quad_double` only. The quad double perf is already set up in the relevant file.

OK on the rest, but really, Fahad, we have already accomplished way more than i had expected in this short GSoC. So please feel free to let any of those points postpone till post GSoC.

@sinandredemption

**Comment by cosurgi** [comment]
I agree with @ckormanyos , main focus is the report right now. We will keep working on it post GSoC. I feel there will be some bumps on the road with full RNG in the de/recomposition tests.

**Comment by sinandredemption** [comment]
Question: Should we mention about papers describing double-float/quad-float algorithms in the GSoC report? If so, which ones?
Options (feel free to add):
- [Shewchuk](https://people.eecs.berkeley.edu/~jrs/papers/robustr.pdf)
- [David Bailey's paper introducing QD](https://web.mit.edu/tabbott/Public/quaddouble-debian/qd-2.3.4-old/docs/qd.pdf)

**Comment by ckormanyos** [comment]
> Should we mention about papers describing double-float/quad-float algorithms in the GSoC report

Yes if you like. Many GSoC particupants place a small introductory section in the report which:
- states the problem to solve,
- reviews the current literature and existing solutions
- describes how ours fits into/adapts from/adds to/improves on these

@sinandredemption

Cc: @cosurgi
