### ISSUE TITLE
Define convenience types cpp_double_flt, cpp_quad_dbl, etc.

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#95]
Define convenience types within the `boost::multirpecision` namespace within the presence of `cpp_double_float.hpp` or `cpp_double_quad.hpp`

Suggest the names (within `cpp_double_float.hpp`):
- `boost::multiprecision::cpp_double_flt`
- `boost::multiprecision::cpp_double_dbl`
- `boost::multiprecision::cpp_double_ldbl`
- `boost::multiprecision::cpp_double_f128`

Suggest the names (within `cpp_quad_float.hpp`):
- `boost::multiprecision::cpp_quad_dbl`
- `boost::multiprecision::cpp_quad_ldbl`
- `boost::multiprecision::cpp_quad_f128`

**Comment by ckormanyos** [comment]
Suggestion(s) for the actual names are welcome, or confirmation that the above is OK.

Cc: @sinandredemption and @cosurgi

**Comment by sinandredemption** [comment]
How about dropping the shorthand?
`boost::multiprecision::cpp_double_float`
`boost::multiprecision::cpp_double_double`
`boost::multiprecision::cpp_double_ldouble`
`boost::multiprecision::cpp_double_float128`

**Comment by cosurgi** [comment]
I prefer @sinandredemption suggestion. For simple reason: if the name is shortened somehow, you need to remember how it was shortened (e.g. `cpp_double_flt`). Having a full name such as `cpp_double_float` requires no extra remembering. But I think we have a name conflict with these names: `cpp_double_float` is already used as template. We could rename the template to `cpp_double_fp<…>` and `cpp_quad_fp<…>` since they will be more rarely used - we will use these convenience names instead.

**Comment by ckormanyos** [comment]
>> dropping the shorthand?

I like it. Agreed.

> name conflict with these names: cpp_double_float is already used as template.

The name conflict _is_ actually theoretically resolved at this time. Consider `boost::multiprecision::backends::cpp_double_float`, etc.

At the moment, we are resolved (albeit with mental ambiguity and potential for confusion) with:

```
namespace boost { namespace multiprecision { namespace backends {

template<...> class cpp_double_float;
template<...> class cpp_quad_float;

} }

using cpp_double_float = number<backends::cpp_double_float<float>>;

}
```

1. To be on the safe side, we could append the suffix `_backend` to the already existing classes.
2. Or we could simply run with it the way it is and use Fahad suggested names. In this case, I do not know _how_ confusing the mental ambiguity would be...

Cc: @sinandredemption and @cosurgi

**Comment by sinandredemption** [comment]
> To be on the safe side, we could append the suffix _backend to the already existing classes.

Here, I think to further avoid confusion, I would suggest using @cosurgi's style naming: `cpp_double_fp_backend` and `cpp_quad_fp_backend`. Needless to say, please feel free to criticize this suggestion.

**Comment by ckormanyos** [comment]
>  to further avoid confusion, I would suggest using @cosurgi's style naming: `cpp_double_fp_backend` and `cpp_quad_fp_backend`

I like that too.

So is the following the consensus?
- Rename `template<> class cpp_double_float` to `template<> class cpp_double_fp_backend`.
- Rename `template<> class cpp_quad_float` to `template<> class cpp_quad_fp_backend`.

Use convenience names

For double-float
- `boost::multiprecision::cpp_double_float`
- `boost::multiprecision::cpp_double_double`
- `boost::multiprecision::cpp_double_long_double`
- `boost::multiprecision::cpp_double_float128`

For quad-float
- `boost::multiprecision::cpp_quad_double`
- `boost::multiprecision::cpp_quad_long_double`
- `boost::multiprecision::cpp_quad_float128`

If @sinandredemption and @cosurgi confirm, then we can do the name change ASAP...

**Comment by cosurgi** [comment]
Yes, I like these new names very much! :)

**Comment by ckormanyos** [comment]
> like these new names very much!

OK great @sinandredemption and @cosurgi this is now agreed.

I will wait for a little peaceful time and then do a big renaming operation in the classes and the tests and examples.
